services:
  pds:
    container_name: pds
    image: ghcr.io/samanthavbarron/pds:latest
    restart: unless-stopped
    volumes:
      - ./pds/data:/pds
      - ./pds.env:/config/pds.env
    env_file:
      - ./pds.env
    ports:
      - 8080:3000